
name: Deploy

on: [push]

jobs:
  build:
    name: 'Portfolio deploy'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/spa/*"
          target: "/home/${{ secrets.USERNAME }}/projects/portfolio/www/html"
          rm: true
          overwrite: true

      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: ls
